FROM ruby:3.1.2-alpine3.16

WORKDIR /goclimb

RUN apk add --update \
            git=2.36.2-r0 \
            --no-cache build-base=0.5-r3 \
            --no-cache gcompat=1.0.0-r4 \
            tzdata=2022c-r0 \
            nodejs=16.16.0-r0 \
            yarn=1.22.19-r0

# Application dependencies
COPY package.json yarn.lock ./
RUN yarn install

COPY Gemfile Gemfile.lock ./
RUN bundle

# RUN service nginx reload
# RUN service nginx start
ARG RAILS_ENV="production"
ARG NODE_ENV="production"
ENV RAILS_ENV="${RAILS_ENV}" \
    NODE_ENV="${NODE_ENV}"

# RUN adduser deploy


# This container exposes port 3000 on localhost
EXPOSE 3000
