FROM --platform=amd64 ruby:3.1.2-alpine3.16

WORKDIR /goclimb

RUN apk add --update \
            git=2.36.2-r0 \
            libpq-dev=14.5-r0 \
            --no-cache build-base=0.5-r3 \
            --no-cache gcompat=1.0.0-r4 \
            tzdata=2022c-r0 \
            nodejs \
            yarn=1.22.19-r0

# Application dependencies
COPY package.json yarn.lock ./
RUN yarn install
COPY Gemfile Gemfile.lock ./
RUN bundle

# precompiling assets to make the rails server 🔥fast
COPY . .
RUN rails assets:precompile

# This container exposes port 3000 on localhost
EXPOSE 3000
