meta_product_name: "GoClimb"
meta_title: "GoClimb - Go climbing & make friends!"
meta_description: "Goclimb is the place where you can go climbing to new places with new people."
meta_image: "karabiner_offen.jpg"
